"""Shared error codes for the fastapi-sbert service (Modules 1, 3, 4).

The same constants appear in Spring Boot (Module3ErrorCodes.java) and in the
frontend banner output so that one failure surfaces with the same string
everywhere it is logged."""

from __future__ import annotations

# ─── Module 1 — Business Input & Classification ──────────────────────────────
MOD1_ML_LOAD_FAIL       = "MOD1_ML_LOAD_FAIL"
MOD1_ML_INFERENCE_FAIL  = "MOD1_ML_INFERENCE_FAIL"

# ─── Module 3 — Submodule 3.1: Content Generation ────────────────────────────
MOD31_CONTENT_PROFILE_NOT_FOUND = "MOD31_CONTENT_PROFILE_NOT_FOUND"
MOD31_CONTENT_GENERATION_FAILED = "MOD31_CONTENT_GENERATION_FAILED"
MOD31_CONTENT_STORED            = "MOD31_CONTENT_STORED"
MOD31_CONTENT_APPROVED          = "MOD31_CONTENT_APPROVED"
MOD31_SERP_UNAVAILABLE          = "MOD31_SERP_UNAVAILABLE"
MOD31_LLM_UNAVAILABLE           = "MOD31_LLM_UNAVAILABLE"
MOD31_CAPTION_AGENT_FAILED      = "MOD31_CAPTION_AGENT_FAILED"

# ─── Module 3 — Submodule 3.2: Creative Direction ────────────────────────────
MOD32_CREATIVE_GENERATION_FAILED  = "MOD32_CREATIVE_GENERATION_FAILED"
MOD32_CREATIVE_MISSING_DEPENDENCY = "MOD32_CREATIVE_MISSING_DEPENDENCY"
MOD32_CREATIVE_STORED             = "MOD32_CREATIVE_STORED"
MOD32_CREATIVE_APPROVED           = "MOD32_CREATIVE_APPROVED"

# ─── Module 3 — Gemini / content shared ──────────────────────────────────────
MOD3_CONTENT_GEMINI_DISABLED  = "MOD3_CONTENT_GEMINI_DISABLED"
MOD3_CONTENT_GEMINI_EMPTY     = "MOD3_CONTENT_GEMINI_EMPTY"
MOD3_CONTENT_GEMINI_EXCEPTION = "MOD3_CONTENT_GEMINI_EXCEPTION"

MOD3_COMPLIANCE_GEMINI_DISABLED  = "MOD3_COMPLIANCE_GEMINI_DISABLED"
MOD3_COMPLIANCE_GEMINI_EMPTY     = "MOD3_COMPLIANCE_GEMINI_EMPTY"
MOD3_COMPLIANCE_GEMINI_EXCEPTION = "MOD3_COMPLIANCE_GEMINI_EXCEPTION"
MOD3_COMPLIANCE_VALIDATION       = "MOD3_COMPLIANCE_VALIDATION"
MOD33_OMCS_AGENT_FAILED          = "MOD33_OMCS_AGENT_FAILED"

MOD3_CREATIVE_GEMINI_DISABLED  = "MOD3_CREATIVE_GEMINI_DISABLED"
MOD3_CREATIVE_GEMINI_EMPTY     = "MOD3_CREATIVE_GEMINI_EMPTY"
MOD3_CREATIVE_GEMINI_EXCEPTION = "MOD3_CREATIVE_GEMINI_EXCEPTION"
