"""Shared error codes. The same constants appear in Spring Boot
(Module3ErrorCodes.java) and in the frontend banner output so that one
failure surfaces with the same string everywhere it is logged."""

from __future__ import annotations

# ─── Module 3 — Submodule 3.1: Content Generation ────────────────────────────
MOD31_CONTENT_PROFILE_NOT_FOUND = "MOD31_CONTENT_PROFILE_NOT_FOUND"
MOD31_CONTENT_GENERATION_FAILED = "MOD31_CONTENT_GENERATION_FAILED"
MOD31_CONTENT_STORED            = "MOD31_CONTENT_STORED"
MOD31_CONTENT_APPROVED          = "MOD31_CONTENT_APPROVED"
MOD31_SERP_UNAVAILABLE          = "MOD31_SERP_UNAVAILABLE"

# ─── Module 3 — Submodule 3.2: Creative Direction ────────────────────────────
MOD32_CREATIVE_GENERATION_FAILED  = "MOD32_CREATIVE_GENERATION_FAILED"
MOD32_CREATIVE_MISSING_DEPENDENCY = "MOD32_CREATIVE_MISSING_DEPENDENCY"
MOD32_CREATIVE_STORED             = "MOD32_CREATIVE_STORED"
MOD32_CREATIVE_APPROVED           = "MOD32_CREATIVE_APPROVED"

# ─── Module 3 — Gemini / content shared ──────────────────────────────────────
MOD3_CONTENT_GEMINI_DISABLED  = "MOD3_CONTENT_GEMINI_DISABLED"
MOD3_CONTENT_GEMINI_EMPTY     = "MOD3_CONTENT_GEMINI_EMPTY"
MOD3_CONTENT_GEMINI_EXCEPTION = "MOD3_CONTENT_GEMINI_EXCEPTION"

MOD3_COMPLIANCE_GEMINI_DISABLED  = "MOD3_COMPLIANCE_GEMINI_DISABLED"
MOD3_COMPLIANCE_GEMINI_EMPTY     = "MOD3_COMPLIANCE_GEMINI_EMPTY"
MOD3_COMPLIANCE_GEMINI_EXCEPTION = "MOD3_COMPLIANCE_GEMINI_EXCEPTION"
MOD3_COMPLIANCE_VALIDATION       = "MOD3_COMPLIANCE_VALIDATION"

MOD3_CREATIVE_GEMINI_DISABLED  = "MOD3_CREATIVE_GEMINI_DISABLED"
MOD3_CREATIVE_GEMINI_EMPTY     = "MOD3_CREATIVE_GEMINI_EMPTY"
MOD3_CREATIVE_GEMINI_EXCEPTION = "MOD3_CREATIVE_GEMINI_EXCEPTION"

# ─── Module 2.1 — Market Data Aggregation ────────────────────────────────────
MOD21_PYTRENDS_UNAVAILABLE   = "MOD21_PYTRENDS_UNAVAILABLE"
MOD21_EXTERNAL_API_ERROR     = "MOD21_EXTERNAL_API_ERROR"
MOD21_ENRICHED_DATASET_EMPTY = "MOD21_ENRICHED_DATASET_EMPTY"
MOD21_INGESTION_JOB_FAILED   = "MOD21_INGESTION_JOB_FAILED"

# ─── Module 2.2 — Forecasting and Market Scoring ─────────────────────────────
MOD22_FORECAST_MAPE_WARNING  = "MOD22_FORECAST_MAPE_WARNING"
MOD22_SCORING_FAILED         = "MOD22_SCORING_FAILED"
MOD22_PROFILE_NOT_READY      = "MOD22_PROFILE_NOT_READY"
