import json
import logging
import os
import re
from typing import TypedDict, Dict, Any
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, SystemMessage
from app.agents.omcs_agent.state import CeviewValidationState

load_dotenv()
logger = logging.getLogger(__name__)

# The omcs_agent needs a VISION-capable model because nodes pass the pubmat
# image as an image_url content block. The shared AgentLLMModel default
# (openai/gpt-oss-120b) is text-only and rejects multimodal input, so this
# agent uses its own Groq vision model. Overridable via OMCS_VISION_MODEL.
# Kept isolated so other agents (caption generation, PES report) are unaffected.
_VISION_MODEL = os.environ.get("OMCS_VISION_MODEL", "meta-llama/llama-4-scout-17b-16e-instruct")

_llm = None


def get_llm():
    """Lazily build the Groq vision model on first use.

    Lazy so it picks up GROQ_API_KEY after the app's dotenv load, and so a
    missing key fails at call time (clean error code) rather than import time.
    """
    global _llm
    if _llm is None:
        api_key = os.environ.get("GROQ_API_KEY", "")
        if not api_key:
            logger.error("omcs_agent: GROQ_API_KEY missing — vision LLM unavailable.")
            return None
        try:
            from langchain_groq import ChatGroq  # type: ignore[import]
            # max_tokens: without a cap, langchain's JsonOutputParser silently
            # repairs a truncated response by dropping the last incomplete key
            # rather than raising — a growing rubric or rationale field could
            # someday truncate the same way the caption matrix did in
            # AgentLLMModel before this was added there. Cheap to guard now.
            _llm = ChatGroq(model=_VISION_MODEL, temperature=0.4, groq_api_key=api_key, max_tokens=2048)
        except Exception as exc:  # pragma: no cover - import/config failure
            logger.error("omcs_agent: failed to init vision LLM (%s): %s", _VISION_MODEL, exc)
            return None
    return _llm


def _extract_json(text: str) -> dict:
    """Extract the first JSON object from an LLM response.

    llama-4-scout frequently wraps its output in prose or markdown fences even
    when instructed otherwise. A bare json.loads() on that text raises an
    exception and the caller silently returns 0.0. This helper finds the first
    {...} block anywhere in the response so scores are never silently zeroed.
    """
    text = text.strip()
    # Try the whole string first (fast path when the model behaves)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    # Strip common markdown fences then retry
    text = re.sub(r"```(?:json)?", "", text).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    # Last resort: pull the first {...} block out of surrounding prose
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group())
        except json.JSONDecodeError:
            pass
    return {}


def _clean_image_url(url: str) -> str:
    """Strip whitespace and newlines Postman/copy-paste may embed in data: URLs.

    Groq's image decoder rejects base64 with any embedded whitespace, which
    commonly appears when a long data: URL is pasted into Postman's JSON editor
    or generated by encoders that wrap at 76 characters.
    """
    if url.startswith("data:"):
        prefix, _, b64 = url.partition(",")
        return prefix + "," + "".join(b64.split())
    return url.strip()


# 2. Define the Nodes
def node_profile_diff(state: CeviewValidationState) -> dict:
    return {"profile_semantic_score": 85.5}

def node_evaluate_rubric(state: CeviewValidationState) -> dict:
    system_prompt = SystemMessage(content="""
You are an expert marketing quality auditor. Evaluate the asset using the Pubmat–Recommendation Alignment Rubric.
OUTPUT ONLY VALID JSON.
Required Schema:
{
  "scores": {
      "visual_business_context_match": float,
      "visual_intent_consistency": float,
      "tone_visual_mood_alignment": float,
      "psychological_strategy_support": float,
      "target_audience_fit": float,
      "platform_suitability": float,
      "attribute_coverage_consistency": float
  },
  "total": float
}
""")
    recs_str = json.dumps(state['recommendations'], indent=2)
    human_text = f"Recommendations Context:\n{recs_str}\n\nEvaluate the image."
    
    message = HumanMessage(content=[
        {"type": "text", "text": human_text},
        {"type": "image_url", "image_url": {"url": _clean_image_url(state["image_url"])}}
    ])

    response = get_llm().invoke([system_prompt, message])
    logger.debug("node_evaluate_rubric raw response: %s", response.content[:400])

    evaluation_data = _extract_json(response.content)
    if not evaluation_data or "scores" not in evaluation_data:
        logger.warning("node_evaluate_rubric: JSON extraction failed; raw=%s", response.content[:200])
        evaluation_data = {"error": "Parse failed", "raw": response.content}
    total_score = float(evaluation_data.get("total", 0.0))

    return {
        "rubric_evaluation_data": evaluation_data,
        "recommendations_picture_score": total_score
    }

def node_check_consistency(state: CeviewValidationState) -> dict:
    system_prompt = SystemMessage(content="""
Analyze consistency between caption and image (Tone, Alignment, Category).
OUTPUT ONLY VALID JSON.
Schema:
{
    "consistency_score": float,  // 0 to 100
    "rationale": "string explanation"
}
""")
    human_text = f"Caption: \"{state['caption']}\"\nAnalyze consistency."
    
    message = HumanMessage(content=[
        {"type": "text", "text": human_text},
        {"type": "image_url", "image_url": {"url": _clean_image_url(state["image_url"])}}
    ])
    response = get_llm().invoke([system_prompt, message])
    logger.debug("node_check_consistency raw response: %s", response.content[:400])

    data = _extract_json(response.content)
    if data:
        score = float(data.get("consistency_score", 0.0))
        text = data.get("rationale", "No rationale provided.")
    else:
        logger.warning("node_check_consistency: JSON extraction failed; raw=%s", response.content[:200])
        score = 0.0
        text = response.content

    return {
        "pubmat_consistency_score": score,
        "consistency_explanation": text
    }

def node_calculate_omcs(state: CeviewValidationState) -> dict:
    """Calculates OMCS and explicitly sets the pass/fail status here."""
    p_score = state.get('profile_semantic_score', 0)
    r_score = state.get('recommendations_picture_score', 0) * 100
    c_score = state.get('pubmat_consistency_score', 0)
    
    OMCS = (0.35 * p_score) + (0.45 * r_score) + (0.20 * c_score)
    
    # Set the status immediately so it's available even if we skip the feedback node
    status = "Pass" if OMCS >= 70 else "Fail"
    
    # If it passes, pre-fill feedback so it isn't completely empty
    feedback = "Asset approved." if status == "Pass" else ""
    
    return {
        "omcs_score": OMCS, 
        "status": status,
        "feedback": feedback
    } 

def node_generate_feedback(state: CeviewValidationState) -> dict:
    """This node is now ONLY called if the OMCS score is a Fail."""
    score = state.get("omcs_score", 0)
    
    system_prompt = """You are an expert QA Evaluator. The asset has FAILED the OMCS check.
Provide Root Cause Analysis and bulleted Actionable Fixes. No filler."""

    human_prompt = f"""
OMCS Score: {score:.2f}/100
- Profile Semantic Score: {state.get('profile_semantic_score')}
- Rubric Total: {state.get('recommendations_picture_score')}
- Consistency Score: {state.get('pubmat_consistency_score')} | Rationale: {state.get('consistency_explanation')}

Generate the failure diagnostic report.
"""
    response = get_llm().invoke([SystemMessage(content=system_prompt), HumanMessage(content=human_prompt)])
    
    return {"feedback": response.content}

# Conditional Routing Logic
def route_omcs_outcome(state: CeviewValidationState) -> str:
    """Evaluates the OMCS score to decide the next step."""
    if state.get("omcs_score", 0) >= 70:
        return "PASS"  # Immediately terminate on Pass
    else:
        return "FAIL"  # Route to feedback on Fail
